on: [push]

jobs:
  basic_unit_test:
    name: "Unit Test"
    concurrency: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Unit tests"
        run:  |
          go get
          go test .
  on_k8s_test:
    name: "Deploy to K8s"
    concurrency: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gambtho/aks_create_action@master
        with:
          CLUSTER_NAME: "actionTest"
          RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
          STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
          STORAGE_CONTAINER_NAME: ${{ secrets.STORAGE_CONTAINER_NAME }}
          STORAGE_ACCESS_KEY: ${{ secrets.STORAGE_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}