on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n acraks02test -g acraks02test9c4b-rg --location "West US 2" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n acraks02test --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n acraks02test --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n acraks02test --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: acraks02test.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acraks02test.azurecr.io/aks02ghtest:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push acraks02test.azurecr.io/aks02ghtest:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_aks02ghtest_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks02-gh-testaca8 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks02-gh-testaca8`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks02-gh-testaca8
        container-registry-url: acraks02test.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: aks02ghtestdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks02-gh-testaca8
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          acraks02test.azurecr.io/aks02ghtest:${{ github.sha }}
        imagepullsecrets: |
          aks02ghtestdockerauth   
